# Generated by Django 5.1.3 on 2025-01-19 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr_payroll', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('employee', 'date')},
        ),
    ]
