# Generated by Django 5.1.3 on 2025-01-19 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_payroll', '0006_payroll_status_salarypayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarypayment',
            name='balance_due',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
