# Generated by Django 5.1.3 on 2025-01-19 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_payroll', '0008_remove_payroll_overtime_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='net_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
