# Generated by Django 5.1.4 on 2025-02-10 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0001_initial'),
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionrun',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervised_runs', to='employee_management.employee'),
        ),
    ]
