# Generated by Django 5.1.4 on 2025-02-10 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_employee_skills_remove_employee_user_and_more'),
        ('production', '0002_alter_productionrun_supervisor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
