# Generated by Django 5.1.4 on 2024-12-13 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('concrete_blocks', 'Concrete Blocks: Hollow blocks for versatile construction.'), ('drainage_solutions', 'Drainage Solutions: Invert blocks, shallow drains, road kerbs, channels, etc.'), ('landscaping_products', 'Landscaping Products: Paving slabs, side slabs, quadrants, and wall copings.'), ('manhole_components', 'Manhole Components: Rings, covers, cover slabs, and tapers.'), ('custom_pavers', 'Custom Pavers: Decorative and functional paving options.')], max_length=100),
        ),
    ]
